# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='developer',
            field=models.CharField(default='china', max_length=120),
            preserve_default=False,
        ),
    ]
